#!/bin/ash
# load-balance(N-WAN) Script VER 1.1i 2011.4.4 for openwrt  by QQ GROUP 120752328

 logpath=/tmp/nwan_log

 
case "$ACTION" in
	ifup)
	[  "${INTERFACE}" != "lan" -o "${INTERFACE}" != "loopback" ] && sh /lib/nwan/route ifup_start	 
	 ;;
	 ifdown)
	   sh /lib/nwan/route ifdown_start
	;;
esac

